---
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
script: nosetests
cache: pip
deploy:
  provider: lambda
  function_name: "lambda-test"
  role: "arn:aws:iam::609459096019:role/service-role/radradradScraper"
  handler_name: "lambdatest.lambda_handler"
  access_key_id: "AKIAID4OY7CSRFAZBOQA"
  secret_access_key: "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"
